apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
spec:
  applicationImage: "default-route-openshift-image-registry.apps-crc.testing/ospoc/service:latest"
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 3Gi
  replicas: 2
metadata:
  name: b
