apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: server
spec:
  applicationImage: "default-route-openshift-image-registry.apps-crc.testing/server:latest"
  replicas: 2
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 3Gi
